name = "minicrm-license"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "LICENSES"
id = "96a860a9b6e24aca977bcc9a6cfa5d39"

[[kv_namespaces]]
binding = "LEADS"
id = "0f1511a43d9f45fc9c8d994525fdd91a"

[[kv_namespaces]]
binding = "TENANTS"
id = "d20f9f1512314f99a58c25786678e916"

[[kv_namespaces]]
binding = "BUGS"
id = "537a7c51537041059e81d4471cb05a5c"

[vars]
# Set the actual admin secret via:
#   npx wrangler secret put ADMIN_SECRET
